; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Jun 05 2022 16:11:22 GMT+0200 (Central European Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


