; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Jun 05 2022 16:11:23 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

