"""create_pen_types_table

Revision ID: b748509b6d21
Revises: 
Create Date: 2025-12-10 22:13:25.098179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b748509b6d21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pen_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('pen_up', sa.Float(), nullable=False),
    sa.Column('pen_down', sa.Float(), nullable=False),
    sa.Column('pump_distance_threshold', sa.Float(), nullable=False),
    sa.Column('pump_height', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pen_types_id'), 'pen_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pen_types_id'), table_name='pen_types')
    op.drop_table('pen_types')
    # ### end Alembic commands ###
